import { desc, eq } from "drizzle-orm";
import { createDiscountCodeAction, createGiftVoucherAction, createMembershipAction, createPackageAction, createReferralCampaignAction, redeemGiftVoucherAction, toggleDiscountCodeAction } from "@/actions/marketing";
import { db } from "@/db";
import { discountCodes, giftVouchers, memberships, referralCampaigns, servicePackages } from "@/db/marketing-schema";
import { services } from "@/db/schema";
import { requireSession } from "@/lib/session";
import { euro } from "@/lib/utils";

export default async function Page() {
  const session = await requireSession();
  const [discounts, referrals, vouchers, membershipRows, packages, serviceRows] = await Promise.all([
    db.query.discountCodes.findMany({ where: eq(discountCodes.salonId, session.salonId), orderBy: [desc(discountCodes.createdAt)] }),
    db.query.referralCampaigns.findMany({ where: eq(referralCampaigns.salonId, session.salonId), orderBy: [desc(referralCampaigns.createdAt)] }),
    db.query.giftVouchers.findMany({ where: eq(giftVouchers.salonId, session.salonId), orderBy: [desc(giftVouchers.createdAt)] }),
    db.query.memberships.findMany({ where: eq(memberships.salonId, session.salonId), orderBy: [desc(memberships.createdAt)] }),
    db.query.servicePackages.findMany({ where: eq(servicePackages.salonId, session.salonId), orderBy: [desc(servicePackages.createdAt)] }),
    db.query.services.findMany({ where: eq(services.salonId, session.salonId) }),
  ]);

  return <>
    <div style={{ marginBottom: 24 }}><span className="badge">Revenue tools</span><h1 style={{ marginBottom: 8 }}>Marketing &amp; offers</h1><p style={{ color: "var(--muted)", maxWidth: 780 }}>Create offers that drive repeat bookings without giving away margin. Every product has clear limits, balances and expiry controls.</p></div>

    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(300px,1fr))", gap: 18 }}>
      <form action={createDiscountCodeAction} className="card" style={{ padding: 22, display: "grid", gap: 12 }}><h2>Discount code</h2><input className="input" name="code" placeholder="WELCOME10" required /><input className="input" name="description" placeholder="New client welcome offer" /><div className="grid-auto"><select className="input" name="type"><option value="percent">Percentage</option><option value="fixed">Fixed € amount</option></select><input className="input" type="number" min="1" step="0.01" name="amount" placeholder="10" required /></div><div className="grid-auto"><input className="input" type="number" min="0" step="0.01" name="minimumSpend" placeholder="Minimum spend €" /><input className="input" type="number" min="1" name="maximumRedemptions" placeholder="Maximum uses" /></div><div className="grid-auto"><label><span className="label">Starts</span><input className="input" type="datetime-local" name="startsAt" /></label><label><span className="label">Ends</span><input className="input" type="datetime-local" name="endsAt" /></label></div><button className="btn btn-primary">Create discount</button></form>

      <form action={createReferralCampaignAction} className="card" style={{ padding: 22, display: "grid", gap: 12 }}><h2>Referral campaign</h2><input className="input" name="name" placeholder="Refer a friend" required /><div className="grid-auto"><label><span className="label">Existing client reward (€)</span><input className="input" type="number" min="0" step="0.01" name="advocateReward" defaultValue="10" required /></label><label><span className="label">Friend reward (€)</span><input className="input" type="number" min="0" step="0.01" name="friendReward" defaultValue="10" required /></label></div><textarea className="input" name="terms" rows={4} placeholder="Reward applies after the referred client completes and pays for their first appointment." /><button className="btn btn-primary">Create campaign</button></form>

      <form action={createGiftVoucherAction} className="card" style={{ padding: 22, display: "grid", gap: 12 }}><h2>Gift voucher</h2><div className="grid-auto"><input className="input" type="number" min="1" step="0.01" name="amount" placeholder="Amount €" required /><input className="input" name="recipientName" placeholder="Recipient name" required /></div><input className="input" type="email" name="recipientEmail" placeholder="Recipient email" /><div className="grid-auto"><input className="input" name="purchaserName" placeholder="Purchaser name" /><input className="input" type="email" name="purchaserEmail" placeholder="Purchaser email" /></div><textarea className="input" name="message" rows={3} placeholder="Personal message" /><label><span className="label">Expiry date</span><input className="input" type="date" name="expiresAt" /></label><button className="btn btn-primary">Issue voucher</button></form>

      <form action={createMembershipAction} className="card" style={{ padding: 22, display: "grid", gap: 12 }}><h2>Membership</h2><input className="input" name="name" placeholder="Monthly Recovery Club" required /><textarea className="input" name="description" rows={3} placeholder="Two massages each month plus priority booking." /><div className="grid-auto"><label><span className="label">Monthly price (€)</span><input className="input" type="number" min="1" step="0.01" name="price" defaultValue="79" required /></label><label><span className="label">Visits included</span><input className="input" type="number" min="0" name="visitsIncluded" defaultValue="2" required /></label></div><label style={{ display: "flex", gap: 8 }}><input type="checkbox" name="priorityBooking" /> Priority booking benefit</label><button className="btn btn-primary">Create membership</button></form>

      <form action={createPackageAction} className="card" style={{ padding: 22, display: "grid", gap: 12 }}><h2>Service package</h2><input className="input" name="name" placeholder="5 Sports Massages" required /><select className="input" name="serviceId"><option value="">Any agreed service</option>{serviceRows.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select><textarea className="input" name="description" rows={3} placeholder="Five sessions at a package rate." /><div className="grid-auto"><input className="input" type="number" min="2" name="sessionCount" defaultValue="5" required /><input className="input" type="number" min="1" step="0.01" name="price" placeholder="Package price €" required /></div><label><span className="label">Valid for days</span><input className="input" type="number" min="1" name="validityDays" defaultValue="365" required /></label><button className="btn btn-primary">Create package</button></form>
    </div>

    <section className="card table-wrap" style={{ padding: 16, marginTop: 24 }}><h2>Discount codes</h2><table><thead><tr><th>Code</th><th>Offer</th><th>Usage</th><th>Status</th><th /></tr></thead><tbody>{discounts.length === 0 ? <tr><td colSpan={5}>No discount codes yet.</td></tr> : discounts.map((item) => <tr key={item.id}><td><strong>{item.code}</strong><br/><small>{item.description}</small></td><td>{item.type === "percent" ? `${item.amount}%` : euro(item.amount)}{item.minimumSpendCents > 0 ? ` · min ${euro(item.minimumSpendCents)}` : ""}</td><td>{item.redemptionCount}{item.maximumRedemptions ? ` / ${item.maximumRedemptions}` : ""}</td><td><span className="badge">{item.active ? "Active" : "Paused"}</span></td><td><form action={toggleDiscountCodeAction}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="active" value={item.active ? "false" : "true"} /><button className="btn btn-secondary">{item.active ? "Pause" : "Activate"}</button></form></td></tr>)}</tbody></table></section>

    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(340px,1fr))", gap: 18, marginTop: 24 }}>
      <section className="card" style={{ padding: 20 }}><h2>Gift vouchers</h2><div style={{ display: "grid", gap: 12 }}>{vouchers.length === 0 ? <p>No vouchers issued.</p> : vouchers.map((voucher) => <article key={voucher.id} style={{ border: "1px solid var(--border)", borderRadius: 14, padding: 14 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><div><strong>{voucher.code}</strong><p style={{ margin: "5px 0", color: "var(--muted)" }}>{voucher.recipientName}</p></div><div style={{ textAlign: "right" }}><strong>{euro(voucher.balanceCents)}</strong><br/><small>of {euro(voucher.amountCents)}</small></div></div><div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}><a className="btn btn-secondary" href={`/api/vouchers/${voucher.id}/pdf`} target="_blank">Download PDF</a>{voucher.status === "active" && <form action={redeemGiftVoucherAction} style={{ display: "flex", gap: 6 }}><input type="hidden" name="id" value={voucher.id} /><input className="input" name="amount" type="number" min="0.01" step="0.01" placeholder="Redeem €" style={{ width: 110 }} /><button className="btn btn-secondary">Redeem</button></form>}</div></article>)}</div></section>

      <section className="card" style={{ padding: 20 }}><h2>Memberships</h2><div style={{ display: "grid", gap: 12 }}>{membershipRows.length === 0 ? <p>No memberships yet.</p> : membershipRows.map((item) => <article key={item.id} style={{ border: "1px solid var(--border)", borderRadius: 14, padding: 14 }}><strong>{item.name}</strong><h3>{euro(item.priceCents)} / month</h3><p style={{ color: "var(--muted)" }}>{item.description}</p><span className="badge">{item.visitsIncluded} visits</span>{item.priorityBooking && <span className="badge" style={{ marginLeft: 6 }}>Priority booking</span>}</article>)}</div></section>

      <section className="card" style={{ padding: 20 }}><h2>Packages</h2><div style={{ display: "grid", gap: 12 }}>{packages.length === 0 ? <p>No packages yet.</p> : packages.map((item) => <article key={item.id} style={{ border: "1px solid var(--border)", borderRadius: 14, padding: 14 }}><strong>{item.name}</strong><h3>{item.sessionCount} sessions · {euro(item.priceCents)}</h3><p style={{ color: "var(--muted)" }}>{item.description}</p><small>Valid for {item.validityDays} days</small></article>)}</div></section>

      <section className="card" style={{ padding: 20 }}><h2>Referral campaigns</h2><div style={{ display: "grid", gap: 12 }}>{referrals.length === 0 ? <p>No referral campaigns yet.</p> : referrals.map((item) => <article key={item.id} style={{ border: "1px solid var(--border)", borderRadius: 14, padding: 14 }}><strong>{item.name}</strong><p>{euro(item.advocateRewardCents)} for the existing client · {euro(item.friendRewardCents)} for their friend</p><small style={{ color: "var(--muted)" }}>{item.terms}</small></article>)}</div></section>
    </div>
  </>;
}
