import { count, desc, gte, sql } from "drizzle-orm";
import { subDays } from "date-fns";
import { internalLogoutAction } from "@/actions/internal-auth";
import { db } from "@/db";
import { aiGenerations } from "@/db/marketing-schema";
import { applicationErrors, automationExecutions, supportTickets } from "@/db/operations-schema";
import { bookings, reviews, salons } from "@/db/schema";
import { requireInternalPermission } from "@/lib/internal-session";
import { euro } from "@/lib/utils";

export default async function InternalConsole({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const user = await requireInternalPermission("view_platform");
  const query = ((await searchParams).q || "").trim().toLowerCase();
  const since = subDays(new Date(), 30);
  const [businessRows, bookingRows, reviewRows, ticketRows, errorRows, aiRows, automationRows] = await Promise.all([
    db.query.salons.findMany({ orderBy: [desc(salons.createdAt)], limit: 100 }),
    db.query.bookings.findMany({ where: gte(bookings.createdAt, since), with: { salon: true, customer: true }, orderBy: [desc(bookings.createdAt)], limit: 100 }),
    db.query.reviews.findMany({ with: { salon: true }, orderBy: [desc(reviews.createdAt)], limit: 50 }),
    db.query.supportTickets.findMany({ with: { salon: true }, orderBy: [desc(supportTickets.createdAt)], limit: 50 }),
    db.query.applicationErrors.findMany({ orderBy: [desc(applicationErrors.createdAt)], limit: 50 }),
    db.query.aiGenerations.findMany({ where: gte(aiGenerations.createdAt, since), with: { salon: true }, orderBy: [desc(aiGenerations.createdAt)], limit: 50 }),
    db.select({ total: count(), sent: sql<number>`count(*) filter (where ${automationExecutions.status} = 'sent')` }).from(automationExecutions).where(gte(automationExecutions.createdAt, since)),
  ]);
  const businesses = businessRows.filter((row) => !query || [row.name, row.email, row.slug].join(" ").toLowerCase().includes(query));
  const filteredBookings = bookingRows.filter((row) => !query || [row.id, row.salon.name, row.customerId].join(" ").toLowerCase().includes(query));
  const revenue = bookingRows.filter((row) => row.paymentStatus === "paid").reduce((sum, row) => sum + row.depositCents, 0);
  return <main className="container" style={{ padding: "28px 0 70px" }}><header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, flexWrap: "wrap" }}><div><span className="badge">Internal · {user.role.replaceAll("_", " ")}</span><h1>Operations console</h1><p style={{ color: "var(--muted)" }}>Signed in as {user.name}. All sensitive write actions must be audited.</p></div><form action={internalLogoutAction}><button className="btn btn-secondary">Sign out</button></form></header>
    <form role="search" className="card" style={{ padding: 16, display: "flex", gap: 10, margin: "22px 0" }}><input className="input" name="q" defaultValue={query} placeholder="Search businesses, bookings or customer-safe IDs"/><button className="btn btn-primary">Search</button></form>
    <div className="grid-auto" style={{ marginBottom: 22 }}><article className="card" style={{ padding: 18 }}><span className="label">Active businesses</span><strong style={{ fontSize: 30 }}>{businessRows.filter((row) => row.storefrontPublished).length}</strong></article><article className="card" style={{ padding: 18 }}><span className="label">Bookings · 30d</span><strong style={{ fontSize: 30 }}>{bookingRows.length}</strong></article><article className="card" style={{ padding: 18 }}><span className="label">Revenue processed · 30d</span><strong style={{ fontSize: 30 }}>{euro(revenue)}</strong></article><article className="card" style={{ padding: 18 }}><span className="label">Stripe connected</span><strong style={{ fontSize: 30 }}>{businessRows.filter((row) => row.stripeAccountId).length}</strong></article><article className="card" style={{ padding: 18 }}><span className="label">AI generations · 30d</span><strong style={{ fontSize: 30 }}>{aiRows.length}</strong></article><article className="card" style={{ padding: 18 }}><span className="label">Automation sends · 30d</span><strong style={{ fontSize: 30 }}>{Number(automationRows[0]?.sent || 0)}</strong></article><article className="card" style={{ padding: 18 }}><span className="label">Open errors</span><strong style={{ fontSize: 30 }}>{errorRows.filter((row) => !row.resolvedAt).length}</strong></article></div>
    <section className="card" style={{ padding: 20, marginBottom: 20 }}><h2>Businesses</h2><div className="table-wrap"><table><thead><tr><th>Business</th><th>Created</th><th>Stripe</th><th>Charges</th><th>Payouts</th><th>Storefront</th></tr></thead><tbody>{businesses.map((row) => <tr key={row.id}><td><strong>{row.name}</strong><br/><small>{row.email}</small></td><td>{row.createdAt.toLocaleDateString("en-IE")}</td><td>{row.stripeAccountId ? "Connected" : "Not connected"}</td><td>{row.stripeChargesEnabled ? "Enabled" : "Off"}</td><td>{row.stripePayoutsEnabled ? "Enabled" : "Off"}</td><td>{row.storefrontPublished ? "Published" : "Hidden"}</td></tr>)}</tbody></table></div></section>
    <section className="card" style={{ padding: 20, marginBottom: 20 }}><h2>Bookings and payments</h2><div className="table-wrap"><table><thead><tr><th>Safe ID</th><th>Business</th><th>Status</th><th>Attendance</th><th>Payment</th><th>Deposit</th></tr></thead><tbody>{filteredBookings.map((row) => <tr key={row.id}><td>{row.id.slice(0, 8)}</td><td>{row.salon.name}</td><td>{row.status}</td><td>{row.status === "completed" || row.status === "no_show" ? row.status : "Not recorded"}</td><td>{row.paymentStatus}</td><td>{euro(row.depositCents)}</td></tr>)}</tbody></table></div></section>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(min(360px,100%),1fr))", gap: 20 }}><section className="card" style={{ padding: 20 }}><h2>Review moderation</h2>{reviewRows.map((row) => <p key={row.id}><strong>{row.salon.name} · {row.rating}/5</strong><br/><small>{row.approved ? "Approved" : "Awaiting moderation"} · {row.createdAt.toLocaleDateString("en-IE")}</small></p>)}</section><section className="card" style={{ padding: 20 }}><h2>Support queue</h2>{ticketRows.length ? ticketRows.map((row) => <p key={row.id}><strong>{row.subject}</strong><br/><small>{row.salon.name} · {row.priority} · {row.status}</small></p>) : <p>No support tickets.</p>}</section><section className="card" style={{ padding: 20 }}><h2>Application errors</h2>{errorRows.length ? errorRows.map((row) => <p key={row.id}><strong>{row.fingerprint}</strong><br/><small>{row.route || "Unknown route"} · {row.createdAt.toLocaleString("en-IE")}</small></p>) : <p>No logged application errors.</p>}</section><section className="card" style={{ padding: 20 }}><h2>AI usage · 30d</h2>{aiRows.map((row) => <p key={row.id}><strong>{row.salon.name} · {row.task}</strong><br/><small>{String(row.metadata.model || "Model unavailable")} · {row.createdAt.toLocaleString("en-IE")}</small></p>)}</section></div>
  </main>;
}
